server:
  port: 3001
  error:
    include-exception: true
    include-message: ALWAYS
    include-stacktrace: ALWAYS

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}

api:
  audience: ${API_AUDIENCE}
