server:
  port: 3001
  error:
    include-exception: true
    include-message: ALWAYS
    include-stacktrace: ALWAYS

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "health"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}

api:
  audience: ${API_AUDIENCE}
