/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.auth0.regularwebapplicationdemo;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class ApplicationTests {
    @Test
    void applicationLoads() {
        Application application = new Application();
        assertNotNull(application, "app should load");
    }
}
