apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/msuperina/auth0-demo.git
    targetRevision: feat-dockerhub-k3d-argocd
    path: charts/api-webflux-demo
    helm:
      parameters:
      - name: AUTH0_ISSUER
        value: https://dev-flidg5q0.eu.auth0.com/
      - name: API_AUDIENCE
        value: http://localhost:3001/api
  destination:
    server: https://0.0.0.0:6552
    namespace: api-demo
